name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Authenticate with ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: private
        env:
          AWS_REGION: us-east-1
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: front-end
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}




      - name: Deploy to EC2 Auto Scaling Group
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Auto Scaling Group
        env:
          AUTO_SCALING_GROUP_NAME: WEB-Server
          LAUNCH_TEMPLATE_NAME: Web-Server
        run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $AUTO_SCALING_GROUP_NAME --region ${{ env.AWS_REGION }} --launch-template LaunchTemplateName=$LAUNCH_TEMPLATE_NAME
