name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Authenticate with ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: private
        env:
          AWS_REGION: us-east-1
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: front-end
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}




      - name: Deploy to EC2 Auto Scaling Group
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Auto Scaling Group
        env:
          AUTO_SCALING_GROUP_NAME: WEB-Server
          LAUNCH_TEMPLATE_NAME: Web-Server
        run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $AUTO_SCALING_GROUP_NAME --region ${{ env.AWS_REGION }} --launch-template LaunchTemplateName=$LAUNCH_TEMPLATE_NAME

#       - name: Remove old containers and images from EC2 instances
#         env:
#           AUTO_SCALING_GROUP_NAME: WEB-Server
#         run: |
#           INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $AUTO_SCALING_GROUP_NAME --query "AutoScalingGroups[].Instances[].InstanceId" --output text)
#           for INSTANCE_ID in $INSTANCE_IDS; do
#             # Stop and remove existing containers
#             ssh -o StrictHostKeyChecking=no ec2-user@$INSTANCE_ID 'sudo docker stop $(sudo docker ps -q) && sudo docker rm $(sudo docker ps -aq)'

#             # Remove old Docker images
#             ssh -o StrictHostKeyChecking=no ec2-user@$INSTANCE_ID 'sudo docker image prune -a --force'
#           done


      - name: Deploy Docker image to EC2 instances
        env:
          AUTO_SCALING_GROUP_NAME: WEB-Server
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: front-end
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names WEB-Server --query "AutoScalingGroups[].Instances[].InstanceId" --output text)
          for INSTANCE_ID in $INSTANCE_IDS; do
            INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[].Instances[].State.Name" --output text --region ${{ env.AWS_REGION }})
            if [[ $INSTANCE_STATE == "running" ]]; then
              echo "Instance $INSTANCE_ID is in a valid state. Sending command..."
              aws ssm send-command --instance-ids $INSTANCE_ID --document-name "AWS-RunShellScript" --comment "Update Docker image" --parameters "commands=['sudo docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest', 'sudo docker stop \$(sudo docker ps -q)', 'sudo docker rm \$(sudo docker ps -aq)', 'sudo docker run -d -p 3000:3000 ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest']" --region ${{ env.AWS_REGION }}
            else
              echo "Waiting for instance $INSTANCE_ID to be in a valid state..."
              aws ec2 wait instance-status-ok --instance-ids $INSTANCE_ID --region ${{ env.AWS_REGION }}
              echo "Instance $INSTANCE_ID is in a valid state. Sending command..."
              aws ssm send-command --instance-ids $INSTANCE_ID --document-name "AWS-RunShellScript" --comment "Update Docker image" --parameters "commands=['sudo docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest', 'sudo docker stop \$(sudo docker ps -q)', 'sudo docker rm \$(sudo docker ps -aq)', 'sudo docker run -d -p 3000:3000 ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest']" --region ${{ env.AWS_REGION }}
            fi
          done
