name: dev-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      # Add a step to navigate to the "build" directory
      - name: Navigate to Build Directory
        run: cd build

      - name: Copy files to the AWS S3 bucket
        run: |
          aws s3 sync --acl public-read --delete build s3://${{ secrets.AWS_DEV_BUCKET }}

#       - name: Invalidate CloudFront distribution
#         run: |
#           aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_DISTRIBUTION_ID }} --paths '/*'
#           echo "DEPLOYED SUCCESSFULLY"
